name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        cd /root/go/src/cicd/Test-Github-Action-Private-Repo
        git pull origin master
        go build main.go
      
    - name: Test
      run: go test -v

  transition-issue:
    name: Transition Issue
    runs-on: self-hosted
    steps:
    # Login vào jira. Sử dụng 3 key mình thêm vào secrets github
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create new issue
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: TC # Vào project settings để xem key (Hình 1)
        issuetype: Bug # Không được thiếu. Cần tạo trước issuetype trên jira. Nếu không sẽ bị lỗi (Hình 2)
        summary: |
          Summary Đây nè
        description: |
          Description ở trong này nhé

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        transition: "TEST TRANSITION" # Tương tự như TODO, IN PROGRESS, DONE. Miễn sao tên transition đã tồn tại trên jira (hình 3)

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Restart service
        run: ./deploy.sh
          

