name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Build
      run: |
        cd /root/go/src/cicd/Test-Github-Action-Private-Repo
        git pull origin master
        go build main.go
      
    - name: Test
      run: go test -v

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Restart service
        run: ./deploy.sh